# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

include:
  - project: 'tol/tol-core'
    ref: main
    file: '/gitlab/main.yml'

stages:
  - lint
  - unit test
  - deploy

test-package:
  extends: .test-python-package

deploy-package:
  extends: .deploy-python-package
  