# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# Used to set up the build environment
variables:
  CI_COMMIT_SHA: ed-lol # REEEMovd
  CI_REGISTRY: gitlab-registry.internal.sanger.ac.uk/tol/platforms # REEEMovd
  CI_REGISTRY_IMAGE: gitlab-registry.internal.sanger.ac.uk/tol/platforms/tol-sdk # REEEMovd
  DOCKER_IMAGE: $CI_REGISTRY/tol/tol-core/build-base:1.0.0
  DIND_IMAGE: $CI_REGISTRY/tol/tol-core/dind:1.0.2
  GOOGLE_CLIENT_SECRETS: $GOOGLE_CLIENT_SECRETS_DEV
  BUILT_IMAGE: $CI_REGISTRY_IMAGE/tol-sdk-test-image:$CI_COMMIT_SHA
  UUID_PREFIX: $CI_JOB_ID

include:
  - project: 'tol/tol-core'
    ref: v1.3.18
    file: '/gitlab/main.yml'


# Linting is already set in main.yml

stages:
  - lint
  - scan
  - build
  - unit test
  - system test
  - benchmark
  - deploy


build-test-image:
  extends: .build
  variables:
    DOCKERFILE: Dockerfile
    PART: '.'
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    NAME: tol-sdk-test-image
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always

unit-test-python-package:
  extends: .unit-test-python-package
  image: $BUILT_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - exists:
      - "**/test/unit/**/*"

.db-test:
  image: $DOCKER_IMAGE
  extends: .test-python
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ''
    POSTGRES_DB: system_test
    POSTGRES_USER: system_test
    POSTGRES_PASSWORD: system_test
    POSTGRES_HOST_AUTH_METHOD: trust
    DB_URI: postgresql://system_test:system_test@db:5432/system_test
    API_PATH: /api

system-test-python-package:
  extends: .db-test
  stage: system test
  services:
    - name: $DIND_IMAGE
      alias: docker
  environment:
    name: system-test
  variables:
    TEST_TYPE: system
  before_script:
    - cd test/system
    - docker-compose up -d db
    - sleep 5s
    - docker-compose up -d system-test-api-sql system-test-api-elastic
  script:
    - docker-compose run system-test
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - exists:
      - "**/test/system/**/*"

benchmark-python-package:
  image: $DOCKER_IMAGE
  extends: .db-test
  stage: benchmark
  before_script:
    - cd test/system
    - docker compose up -d db
    - sleep 5
    - docker compose up -d system-test-api-sql
    - sleep 5
  script:
    - ls
    - cat docker-compose.yml
    - docker compose run benchmark
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: always

deploy-package:
  extends: .deploy-python-package
