# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# Used to set up the build environment
variables:
  GOOGLE_CLIENT_SECRETS: $GOOGLE_CLIENT_SECRETS_DEV
  BUILT_IMAGE: $CI_REGISTRY_IMAGE/tol-sdk-test-image:$CI_COMMIT_SHA
  PYPI_PACKAGE_NAME: tol-sdk

include:
  - project: 'tol/tol-core'
    ref: v1.7.2
    file: '/gitlab/main.yml'


# Linting is already set in main.yml

stages:
  - lint
  - scan
  - build
  - unit test
  - system test
  - integration test
  - deploy


build-test-image:
  extends: .build
  variables:
    DOCKERFILE: Dockerfile
    PART: '.'
    NAME: tol-sdk-test-image
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: on_success

unit-test-python-package:
  extends: .unit-test-python-package
  image: $BUILT_IMAGE
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: on_success

system-test-python-package:
  extends: .test-python
  image: $DOCKER_IMAGE
  stage: system test
  services:
    - name: $DIND_IMAGE
      alias: docker
  environment:
    name: system-test
  variables:
    TEST_TYPE: system
    POSTGRES_DB: system_test
    POSTGRES_USER: system_test
    POSTGRES_PASSWORD: system_test
    POSTGRES_HOST_AUTH_METHOD: trust
    DB_URI: postgresql://system_test:system_test@db:5432/system_test
    API_PATH: /api
    DOCKER_HOST: "tcp://docker:2376"
    DOCKER_SECURE: "true"
    DOCKER_TLS_VERIFY: "1"
  before_script:
    - cd test/system
    - docker-compose up -d db elastic
    - docker-compose up -d system-test-api-sql system-test-api-elastic
  script:
    - docker-compose run system-test
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: on_success

integration-test-python-package:
  extends: .unit-test-python-package
  image: $BUILT_IMAGE
  stage: integration test
  variables:
    TEST_TYPE: integration
  needs:
    - unit-test-python-package
  rules:
    - if: $CI_COMMIT_REF_NAME == "qa"
      when: never
    - if: $CI_COMMIT_REF_NAME == "staging"
      when: never
    - if: $CI_COMMIT_REF_NAME == "production"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - when: on_success

deploy-package:
  extends: .deploy-python-package

deploy-package-public:
  extends: .deploy-python-package-public
  needs:
    - deploy-package

deploy-doc:
  stage: lint
  image: python:3.12
  script:
  - pip install sphinx sphinx-rtd-theme
  - sphinx-apidoc -o doc/source/ src/tol
  - sphinx-build -b html doc/source public
  artifacts:
    paths:
    - public
  # only:
  # - production
