# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only
version: '3.1'

services:
  tol-sdk-api-unit-test:
    image: python:3.8
    volumes:
      - ./:/app
    command: bash -c "pip3 install /app && pip3 install -r /app/requirements-test.txt && pytest -v /app/test/unit"

  tol-sdk-api-db:
    image: postgres:11
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test-db
    networks:
      - api-base-test-network
    
  tol-sdk-api-system-test:
    image: python:3.8
    command: bash -c "pip3 install /app && python3 -m pip install -r /app/requirements-test.txt && pytest -v /app/test/system/api_base"
    environment:
      - DB_URI=postgresql://test-user:test-password@tol-sdk-api-db:5432/test-db
    volumes:
      - ./:/app
    depends_on:
      - tol-sdk-api-db
    networks:
      - api-base-test-network

networks:
  api-base-test-network:
