# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

services:
    
  tol-sdk-python-unit-test:
    build: .
    command: pytest -v unit

  tol-sdk-python-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test-db
    networks:
      - api-base-test-network

  tol-sdk-python-elastic:
    # NB - the below image is ARM/M1 only.
    image: gitlab-registry.internal.sanger.ac.uk/tol/tol-core/elastic:0.1.0
    ports:
      - 9200:9200
    networks:
      - api-base-test-network
    
  tol-sdk-python-system-test:
    build: .
    command: pytest -vvvx system
    environment:
      - DB_URI=postgresql://test-user:test-password@tol-sdk-python-db:5432/test-db
      - UUID_PREFIX=${UUID_PREFIX}
      - ELASTIC_URI=http://tol-sdk-python-elastic:9200
      - ELASTIC_USER=elastic
      # needs to be set, but doesn't matter at all
      - ELASTIC_PASSWORD=anything
      - ELASTIC_INDEX_PREFIX=test
    depends_on:
      - tol-sdk-python-db
      - tol-sdk-python-elastic
      - system-test-api-elastic
      - system-test-api-sql
    networks:
      - api-base-test-network

  system-test-api-elastic:
    build: .
    command: flask --app elastic run --host 0.0.0.0 --debugger
    working_dir: /test/system/data_source/services
    environment:
      - UUID_PREFIX=${UUID_PREFIX}
      - ELASTIC_URI=http://tol-sdk-python-elastic:9200
      - ELASTIC_USER=elastic
      # needs to be set, but doesn't matter at all
      - ELASTIC_PASSWORD=anything
      - ELASTIC_INDEX_PREFIX=test
      - FLASK_DEBUG=1
    depends_on:
      - tol-sdk-python-elastic
    networks:
      - api-base-test-network
    ports:
      - '9023:5000'

  system-test-api-sql:
    build: .
    command: flask --app sql run --host 0.0.0.0 --debugger
    working_dir: /test/system/data_source/services
    environment:
      - DB_URI=postgresql://test-user:test-password@tol-sdk-python-db:5432/test-db
      - FLASK_DEBUG=1
    networks:
      - api-base-test-network
    depends_on:
      - tol-sdk-python-db
    ports:
      - '9021:5000'

  tol-sdk-python-integration-test:
    build: .
    command: pytest -vvvx integration
    environment:
      - GOOGLE_CLIENT_SECRETS
      - UUID_PREFIX=${UUID_PREFIX}
      - JIRA_URL
      - JIRA_API_KEY
      - GOAT_URL
      - GOAT_API_PATH
      - MLWH_URI
      - BENCHLING_URL
      - BENCHLING_API_KEY
      - BENCHLING_REGISTRY_ID
      - BENCHLING_PROJECT
      - BENCHLING_FOLDER
      - ENA_URL
      - ENA_USER
      - ENA_PASSWORD
      - ENA_CONTACT_NAME
      - ENA_CONTACT_EMAIL
      - PORTAL_URL
      - PORTAL_API_PATH
    networks:
      - api-base-test-network

networks:
  api-base-test-network:
