# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
# 
# SPDX-License-Identifier: MIT

[metadata]
name = tol-sdk
version = 0.5.0
author = ToL Platforms Team
author_email = tol-platforms@sanger.ac.uk
description = SDK for interaction with ToL services
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.internal.sanger.ac.uk/tol/platforms/tol-sdk
project_urls =
    Jira = https://jira.sanger.ac.uk/secure/RapidBoard.jspa?rapidView=32&projectKey=TOLP
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.7
install_requires =
    requests
	requests_mock
    datetime
    benchling-sdk
    prefect
    Flask==1.1.2
    Werkzeug==1.0.1
    Cython == 0.29.21
    python_dateutil == 2.8.1
    setuptools == 53.0.0
    Flask-SQLAlchemy == 2.4.4
    flask-restx == 0.5.1
    marshmallow == 3.14.1
    flask-marshmallow == 0.14.0
    marshmallow-sqlalchemy == 0.27.0
    marshmallow-jsonapi == 0.24.0
    markupsafe==2.0.1
    itsdangerous==0.24
    jwt
    alembic==1.8.0
    Jinja2==3.0.3
    connexion == 2.14.1
    Click
    fastavro
    more-itertools
    pika
    python-dotenv
    python-snappy
    jira==3.4.1
    lab-share-lib @ git+https://git@github.com/sanger/lab-share-lib.git@develop

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    tol = tol.cli:cli
