# SPDX-FileCopyrightText: 2022 Genome Research Ltd.
# 
# SPDX-License-Identifier: MIT

[metadata]
name = tol-sdk
version = 1.0.23
author = ToL Platforms Team
author_email = tol-platforms@sanger.ac.uk
description = SDK for interaction with ToL services
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.internal.sanger.ac.uk/tol/platforms/tol-sdk
project_urls =
    Jira = https://jira.sanger.ac.uk/secure/RapidBoard.jspa?rapidView=32&projectKey=TOLP
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    cachetools == 5.3.3
    requests == 2.31.0
    python_dateutil >= 2.8.1
    setuptools == 69.0.3
    case-converter==1.1.0
    Click === 8.1.7
    more-itertools == 10.2.0
    pandas == 2.1.4
    openpyxl >= 3.0.10  # STS uses save_virtual_workbook from version 3.0.x
    XlsxWriter == 3.1.9
    xlrd == 2.0.1
    gspread >= 5.12.0
    python-dotenv >= 1.0.1

[options.extras_require]
all =
    %(api_base)s
    %(api_base2)s
    %(benchling)s
    %(elastic)s
    %(irods)s
    %(jira)s
    %(mysql)s
    %(postgresql)s
    %(prefect)s
    %(sciops)s
api_base =
  Flask == 2.2.2
  Werkzeug == 2.2.2
  SQLAlchemy == 2.0.1
  Flask-SQLAlchemy == 3.0.3
  flask-restx == 1.0.5
  marshmallow == 3.19.0
  flask-marshmallow == 0.14.0
  marshmallow-sqlalchemy == 0.28.1
  marshmallow-jsonapi == 0.24.0
api_base2 = 
    Flask == 2.2.2
    Werkzeug == 2.2.2
benchling =
    benchling-sdk
elastic =
    elasticsearch == 7.17.9
irods =
    python-irodsclient == 1.1.6
jira =
    jira==3.4.1
mysql =
    mysql-connector-python
postgresql =
    SQLAlchemy == 2.0.1
    psycopg2-binary == 2.9.9
prefect =
    prefect[gitlab] >= 2
sciops =
    lab-share-lib @ git+https://github.com/sanger/lab-share-lib@v0.1.6#egg=lab-share-lib
    fastavro # Dependency of lab-share-lib
    pika
    python-snappy

[options.packages.find]
where = src

[options.package_data]
tol.benchling.sql =
    *.sql

[options.entry_points]
console_scripts =
    tol = tol.cli:cli
